# coding: utf-8

"""
    Proxmox Virtual Environment API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 8.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pve_client.models.cluster_sdn_list_all_response_data_fabrics_inner import ClusterSdnListAllResponseDataFabricsInner

class TestClusterSdnListAllResponseDataFabricsInner(unittest.TestCase):
    """ClusterSdnListAllResponseDataFabricsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClusterSdnListAllResponseDataFabricsInner:
        """Test ClusterSdnListAllResponseDataFabricsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClusterSdnListAllResponseDataFabricsInner`
        """
        model = ClusterSdnListAllResponseDataFabricsInner()
        if include_optional:
            return ClusterSdnListAllResponseDataFabricsInner(
                area = '',
                csnp_interval = 1,
                digest = '',
                hello_interval = 1,
                id = '',
                ip6_prefix = '807.88.001.2/02',
                ip_prefix = '807.88.001.2/02',
                lock_token = '',
                protocol = 'openfabric'
            )
        else:
            return ClusterSdnListAllResponseDataFabricsInner(
                id = '',
                protocol = 'openfabric',
        )
        """

    def testClusterSdnListAllResponseDataFabricsInner(self):
        """Test ClusterSdnListAllResponseDataFabricsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
