# coding: utf-8

"""
    Proxmox Virtual Environment API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 8.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pve_client.api.nodes_capabilities_api import NodesCapabilitiesApi


class TestNodesCapabilitiesApi(unittest.TestCase):
    """NodesCapabilitiesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NodesCapabilitiesApi()

    def tearDown(self) -> None:
        pass

    def test_capabilities(self) -> None:
        """Test case for capabilities

        Get node-specific QEMU migration capabilities of the node
        """
        pass

    def test_get_capabilities(self) -> None:
        """Test case for get_capabilities

        Node capabilities index
        """
        pass

    def test_get_cpu(self) -> None:
        """Test case for get_cpu

        List all custom and default CPU models
        """
        pass

    def test_get_cpu_flags(self) -> None:
        """Test case for get_cpu_flags

        List of available VM-specific CPU flags
        """
        pass

    def test_qemu_caps_index(self) -> None:
        """Test case for qemu_caps_index

        QEMU capabilities index
        """
        pass

    def test_types(self) -> None:
        """Test case for types

        Get available QEMU/KVM machine types
        """
        pass


if __name__ == '__main__':
    unittest.main()
