# coding: utf-8

"""
    Proxmox Virtual Environment API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 8.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pve_client.models.pve_replication_config import PveReplicationConfig

class TestPveReplicationConfig(unittest.TestCase):
    """PveReplicationConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PveReplicationConfig:
        """Test PveReplicationConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PveReplicationConfig`
        """
        model = PveReplicationConfig()
        if include_optional:
            return PveReplicationConfig(
                network = '807.88.001.2/02',
                type = 'secure'
            )
        else:
            return PveReplicationConfig(
                type = 'secure',
        )
        """

    def testPveReplicationConfig(self):
        """Test PveReplicationConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
