# coding: utf-8

"""
    Proxmox Virtual Environment API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 8.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pve_client.api.nodes_storage_api import NodesStorageApi


class TestNodesStorageApi(unittest.TestCase):
    """NodesStorageApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NodesStorageApi()

    def tearDown(self) -> None:
        pass

    def test_copy(self) -> None:
        """Test case for copy

        Copy a volume
        """
        pass

    def test_create_content(self) -> None:
        """Test case for create_content

        Allocate disk images
        """
        pass

    def test_delete_content(self) -> None:
        """Test case for delete_content

        Delete volume
        """
        pass

    def test_delete_prunebackups(self) -> None:
        """Test case for delete_prunebackups

        Prune backups
        """
        pass

    def test_diridx(self) -> None:
        """Test case for diridx

        diridx
        """
        pass

    def test_download(self) -> None:
        """Test case for download

        Extract a file or directory (as zip archive) from a PBS backup
        """
        pass

    def test_download_url(self) -> None:
        """Test case for download_url

        Download templates, ISO images, OVAs and VM images by using an URL
        """
        pass

    def test_dryrun(self) -> None:
        """Test case for dryrun

        Get prune information for backups
        """
        pass

    def test_get_content(self) -> None:
        """Test case for get_content

        List storage content
        """
        pass

    def test_get_import_metadata(self) -> None:
        """Test case for get_import_metadata

        Get the base parameters for creating a guest which imports data from a foreign importable guest, like an ESXi VM
        """
        pass

    def test_get_list(self) -> None:
        """Test case for get_list

        List files and directories for single file restore under the given path
        """
        pass

    def test_get_storage(self) -> None:
        """Test case for get_storage

        Get status for all datastores
        """
        pass

    def test_info(self) -> None:
        """Test case for info

        Get volume attributes
        """
        pass

    def test_oci_registry_pull(self) -> None:
        """Test case for oci_registry_pull

        Pull an OCI image from a registry
        """
        pass

    def test_read_status(self) -> None:
        """Test case for read_status

        Read storage status
        """
        pass

    def test_rrd(self) -> None:
        """Test case for rrd

        Read storage RRD statistics (returns PNG)
        """
        pass

    def test_rrddata(self) -> None:
        """Test case for rrddata

        Read storage RRD statistics
        """
        pass

    def test_updateattributes(self) -> None:
        """Test case for updateattributes

        Update volume attributes
        """
        pass

    def test_upload(self) -> None:
        """Test case for upload

        Upload templates, ISO images, OVAs and VM images
        """
        pass


if __name__ == '__main__':
    unittest.main()
