# coding: utf-8

"""
    Proxmox Virtual Environment API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 8.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pve_client.api.access_roles_api import AccessRolesApi


class TestAccessRolesApi(unittest.TestCase):
    """AccessRolesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AccessRolesApi()

    def tearDown(self) -> None:
        pass

    def test_create_role(self) -> None:
        """Test case for create_role

        Create new role
        """
        pass

    def test_delete_role(self) -> None:
        """Test case for delete_role

        Delete role
        """
        pass

    def test_get_roles(self) -> None:
        """Test case for get_roles

        Role index
        """
        pass

    def test_read_role(self) -> None:
        """Test case for read_role

        Get role configuration
        """
        pass

    def test_update_role(self) -> None:
        """Test case for update_role

        Update an existing role
        """
        pass


if __name__ == '__main__':
    unittest.main()
