# coding: utf-8

"""
    Proxmox Virtual Environment API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 8.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pve_client.models.pve_link_field import PveLinkField

class TestPveLinkField(unittest.TestCase):
    """PveLinkField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PveLinkField:
        """Test PveLinkField
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PveLinkField`
        """
        model = PveLinkField()
        if include_optional:
            return PveLinkField(
                address = 'C.L.4.W.W.9OHOEhA8IcFQXnuaZcdyyvKX7HzKpul80FcVjSkp5IHYCm6w-v0dZfUofvKERjsmInY9s-EmMH6kw8gsnXv2Z7jRPd.M.Pp8ZohR8k.O.tqEde8fXg9wdpfxa2-zRi2iAxU4C.DvTrirUe4ba7JnjrgEdBCJE-ArE6U3CZ-Vnrj9RmauFxvm.ysCj3.Y.VvKGSDRGKUIQ8yNXhXoEdbZpGptfI4pvLXGuLk-kwwO2jcMEEkIauWe.PaDi5ackLaR2kw9-zmvqRnM-dar09VaHCQz0TlT4b42Jm2.sXN.FO8G0e5q9Z4WMWovY63Gk6ixTd5NxRU25mQYd6VBLRGkQ5H9-FH2v5iUaMQ6iIJ-7auxDSR-lIz.D.PbP3XhsKpT6YkX2ymMP.o.uBx8OyxaBZ75cAidDZ6lvrLQxekRdyiJFjhCbEZunVXTqV3VP-DPQpzY-c9WhD1h649MeAEDz67NG9dihNlL1YPO1z.RDnbsR0-SswaNzc7s9ONPZw-HNd.RykpnotMPK4Aqhv7VjToBNn1oLFT.t.O.yd2clYhZAz.S.aPB5iVX1lhmY7Gh2I3pT2SDuv66tyxEBpX6RQusWUzrY2IaluFJfz8Zwx6YGCNhQCndVdQ8Zqh8o9Fu3K.51PzrlptgIbB7lMjnQXJdim087U4e00bXYPH263P2Qk0LGzQ-Q5b8q5.O.p.1J7NsXeu0SeHiClor8kJwu9CQe1tTxWk3GoxqObZMXxUrUZPuO24g6xCEEGYs5NZ9BhURG1p1vKPKEsak3.Z',
                priority = 0
            )
        else:
            return PveLinkField(
                address = 'C.L.4.W.W.9OHOEhA8IcFQXnuaZcdyyvKX7HzKpul80FcVjSkp5IHYCm6w-v0dZfUofvKERjsmInY9s-EmMH6kw8gsnXv2Z7jRPd.M.Pp8ZohR8k.O.tqEde8fXg9wdpfxa2-zRi2iAxU4C.DvTrirUe4ba7JnjrgEdBCJE-ArE6U3CZ-Vnrj9RmauFxvm.ysCj3.Y.VvKGSDRGKUIQ8yNXhXoEdbZpGptfI4pvLXGuLk-kwwO2jcMEEkIauWe.PaDi5ackLaR2kw9-zmvqRnM-dar09VaHCQz0TlT4b42Jm2.sXN.FO8G0e5q9Z4WMWovY63Gk6ixTd5NxRU25mQYd6VBLRGkQ5H9-FH2v5iUaMQ6iIJ-7auxDSR-lIz.D.PbP3XhsKpT6YkX2ymMP.o.uBx8OyxaBZ75cAidDZ6lvrLQxekRdyiJFjhCbEZunVXTqV3VP-DPQpzY-c9WhD1h649MeAEDz67NG9dihNlL1YPO1z.RDnbsR0-SswaNzc7s9ONPZw-HNd.RykpnotMPK4Aqhv7VjToBNn1oLFT.t.O.yd2clYhZAz.S.aPB5iVX1lhmY7Gh2I3pT2SDuv66tyxEBpX6RQusWUzrY2IaluFJfz8Zwx6YGCNhQCndVdQ8Zqh8o9Fu3K.51PzrlptgIbB7lMjnQXJdim087U4e00bXYPH263P2Qk0LGzQ-Q5b8q5.O.p.1J7NsXeu0SeHiClor8kJwu9CQe1tTxWk3GoxqObZMXxUrUZPuO24g6xCEEGYs5NZ9BhURG1p1vKPKEsak3.Z',
        )
        """

    def testPveLinkField(self):
        """Test PveLinkField"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
