# coding: utf-8

"""
    Proxmox Virtual Environment API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 8.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pve_client.models.cluster_bulk_action_suspend_request import ClusterBulkActionSuspendRequest

class TestClusterBulkActionSuspendRequest(unittest.TestCase):
    """ClusterBulkActionSuspendRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClusterBulkActionSuspendRequest:
        """Test ClusterBulkActionSuspendRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClusterBulkActionSuspendRequest`
        """
        model = ClusterBulkActionSuspendRequest()
        if include_optional:
            return ClusterBulkActionSuspendRequest(
                maxworkers = 56,
                statestorage = 'a6otgfww_r74cm.fyln9uyrj1gzi.0',
                to_disk = 0,
                vms = [
                    100
                    ]
            )
        else:
            return ClusterBulkActionSuspendRequest(
        )
        """

    def testClusterBulkActionSuspendRequest(self):
        """Test ClusterBulkActionSuspendRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
