# coding: utf-8

"""
    Proxmox Virtual Environment API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 8.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pve_client.models.cluster_bulk_action_start_request import ClusterBulkActionStartRequest

class TestClusterBulkActionStartRequest(unittest.TestCase):
    """ClusterBulkActionStartRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClusterBulkActionStartRequest:
        """Test ClusterBulkActionStartRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClusterBulkActionStartRequest`
        """
        model = ClusterBulkActionStartRequest()
        if include_optional:
            return ClusterBulkActionStartRequest(
                maxworkers = 56,
                timeout = 56,
                vms = [
                    100
                    ]
            )
        else:
            return ClusterBulkActionStartRequest(
        )
        """

    def testClusterBulkActionStartRequest(self):
        """Test ClusterBulkActionStartRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
