# coding: utf-8

"""
    Proxmox Virtual Environment API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 8.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pve_client.models.access_groups_read_group_response import AccessGroupsReadGroupResponse

class TestAccessGroupsReadGroupResponse(unittest.TestCase):
    """AccessGroupsReadGroupResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccessGroupsReadGroupResponse:
        """Test AccessGroupsReadGroupResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccessGroupsReadGroupResponse`
        """
        model = AccessGroupsReadGroupResponse()
        if include_optional:
            return AccessGroupsReadGroupResponse(
                data = pve_client.models.access_groups_read_group_response_data.AccessGroupsReadGroupResponse_data(
                    comment = '', 
                    members = [
                        'W@iUUGjjNSwg0_bs9ZayIMrKdgNvb6gvxmPb9GcsM61ate1RA89q3w1l4eH4XxEz.5awxoFZxH'
                        ], ),
                total = 56,
                changes = None
            )
        else:
            return AccessGroupsReadGroupResponse(
                data = pve_client.models.access_groups_read_group_response_data.AccessGroupsReadGroupResponse_data(
                    comment = '', 
                    members = [
                        'W@iUUGjjNSwg0_bs9ZayIMrKdgNvb6gvxmPb9GcsM61ate1RA89q3w1l4eH4XxEz.5awxoFZxH'
                        ], ),
        )
        """

    def testAccessGroupsReadGroupResponse(self):
        """Test AccessGroupsReadGroupResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
