# coding: utf-8

"""
    Proxmox Virtual Environment API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 8.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pve_client.models.cluster_mapping_get_usb_response import ClusterMappingGetUsbResponse

class TestClusterMappingGetUsbResponse(unittest.TestCase):
    """ClusterMappingGetUsbResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClusterMappingGetUsbResponse:
        """Test ClusterMappingGetUsbResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClusterMappingGetUsbResponse`
        """
        model = ClusterMappingGetUsbResponse()
        if include_optional:
            return ClusterMappingGetUsbResponse(
                data = [
                    pve_client.models.cluster_mapping_get_usb_response_data_inner.ClusterMappingGetUsbResponse_data_inner(
                        description = '', 
                        error = null, 
                        id = '', 
                        map = [
                            ''
                            ], )
                    ],
                total = 56,
                changes = None
            )
        else:
            return ClusterMappingGetUsbResponse(
                data = [
                    pve_client.models.cluster_mapping_get_usb_response_data_inner.ClusterMappingGetUsbResponse_data_inner(
                        description = '', 
                        error = null, 
                        id = '', 
                        map = [
                            ''
                            ], )
                    ],
        )
        """

    def testClusterMappingGetUsbResponse(self):
        """Test ClusterMappingGetUsbResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
