# coding: utf-8

"""
    Proxmox Virtual Environment API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 8.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pve_client.models.qemu_vm_resume_response import QemuVmResumeResponse

class TestQemuVmResumeResponse(unittest.TestCase):
    """QemuVmResumeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QemuVmResumeResponse:
        """Test QemuVmResumeResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QemuVmResumeResponse`
        """
        model = QemuVmResumeResponse()
        if include_optional:
            return QemuVmResumeResponse(
                data = '',
                total = 56,
                changes = None
            )
        else:
            return QemuVmResumeResponse(
                data = '',
        )
        """

    def testQemuVmResumeResponse(self):
        """Test QemuVmResumeResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
