# coding: utf-8

"""
    Proxmox Virtual Environment API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 8.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pve_client.models.nodes_sdn_bridges_response import NodesSdnBridgesResponse

class TestNodesSdnBridgesResponse(unittest.TestCase):
    """NodesSdnBridgesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NodesSdnBridgesResponse:
        """Test NodesSdnBridgesResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NodesSdnBridgesResponse`
        """
        model = NodesSdnBridgesResponse()
        if include_optional:
            return NodesSdnBridgesResponse(
                data = [
                    pve_client.models.nodes_sdn_bridges_response_data_inner.NodesSdnBridgesResponse_data_inner(
                        name = '', 
                        ports = [
                            pve_client.models.nodes_sdn_bridges_response_data_inner_ports_inner.NodesSdnBridgesResponse_data_inner_ports_inner(
                                index = '', 
                                name = '', 
                                primary_vlan = 1.337, 
                                vlans = [
                                    ''
                                    ], 
                                vmid = 1.337, )
                            ], 
                        vlan_filtering = '', )
                    ],
                total = 56,
                changes = None
            )
        else:
            return NodesSdnBridgesResponse(
                data = [
                    pve_client.models.nodes_sdn_bridges_response_data_inner.NodesSdnBridgesResponse_data_inner(
                        name = '', 
                        ports = [
                            pve_client.models.nodes_sdn_bridges_response_data_inner_ports_inner.NodesSdnBridgesResponse_data_inner_ports_inner(
                                index = '', 
                                name = '', 
                                primary_vlan = 1.337, 
                                vlans = [
                                    ''
                                    ], 
                                vmid = 1.337, )
                            ], 
                        vlan_filtering = '', )
                    ],
        )
        """

    def testNodesSdnBridgesResponse(self):
        """Test NodesSdnBridgesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
