# coding: utf-8

"""
    Proxmox Virtual Environment API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 8.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pve_client.models.cluster_options_set_options_request import ClusterOptionsSetOptionsRequest

class TestClusterOptionsSetOptionsRequest(unittest.TestCase):
    """ClusterOptionsSetOptionsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClusterOptionsSetOptionsRequest:
        """Test ClusterOptionsSetOptionsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClusterOptionsSetOptionsRequest`
        """
        model = ClusterOptionsSetOptionsRequest()
        if include_optional:
            return ClusterOptionsSetOptionsRequest(
                bwlimit = None,
                consent_text = '',
                console = 'applet',
                crs = None,
                delete = '',
                description = '',
                email_from = '',
                fencing = 'watchdog',
                ha = None,
                http_proxy = 'http://jUR,rZ#UM/?R,Fp^l6$ARj',
                keyboard = 'de',
                language = 'ar',
                mac_prefix = 'BC:24:11',
                max_workers = 1,
                migration = None,
                migration_unsecure = 0,
                next_id = None,
                notify = None,
                registered_tags = 'pqn95oe+ghbs5+i8x65gzc.sv2775vgdci7c5m.z0t60_tp4vclgcolhtfh+.wf-.6h;6.difa45w+hke9q9m27f894.4b2+k84244g-zspo-m.ecuy59p-cw0099yxnql9hprzhhmcu4ojd52m0;5lbc2powytw-bsk5xy1ksvb.5umyds7fpzwfxmo98vdfj;h19o1ozm4r0h52nmtc_z8lj_5s.kptbrm074k27my7lxrni4f02x+3+m3.gwwkfm.1;g1r2ajaaxfnz+266ocyn2zlk7m.38v-az1qh.3s385-688y1d3hx0.jdzwogs.qpgoi2md;2-vdd0+pgkpr-4l5n490ew.snq+0mnega1yr7wdvop05vp6l.ykt8od8mzx-b;eqzkj4svlvro8oc.ai;mmw08-.aoqodhsa.+6_c8hu.s.48-87p5s3b_yd_tj6va24x6chh+tnmqmxtyhd0gq20ypp;ho7lslq.rcfvb6v-ml0hxb-hiygu07ec6losqzy3y2f4.sq15mvvvz0cuhi+qcfhx.0fx9g_7162bnj4ntukvi_k3cddaxhnl11;l9gfyk75m_7yce1z-n0tge5.9u0+tl6a.e6gkg+wx0wovlypm5sr63qziy7354z46fbw7y5_y6lz57uhtelilf-7z0x71;nnl8045lac+mgmv.29ewlu+moe0alcrnb-12d55.zl5n6+zn1_l9pa-+vcb7tg_-l7c;c_10_fk+hylft9vv6k7mu7awumwcf1lec+dmx73h;d2puxfc5mx7g91c53a.uu6onr8e1uqpdnbyta2py-ayjs2dank_ftqty1iy1smwdt8c9+xrctv-ypy1cby1l9f_5w__f+ssrb9cq;p6.bqz_1upfww0rspfmfy+n20vclb0uo6+zpghsvpzvkhafcqkv_f970ktrvkoai_+n56p8qwj0x;t+d1rg3la.jl5tk74xuy1n06x7ctlj5o--2nh1un+tw9m.yv5.xmt0w5bdh0so2+dwnpaxhj+dq2nwc_nn.w8ay--27nti5t_wg5;pubtsmyta-ph0hdx-wlqkubkkxd6_i4c0jsjlfxq7yrsa81g4w1n;27kjsh6m_ztdihbbihi1oqezz69_5pe39+yq2ldlgm1+998ki.;vhca9x9ci2u-daxq74la2z339qr6bb;s2abc5um_4+pux9an;7-7.vjv7i01sqp3n8+wzeybfvn;pdiu43ofgn443d15ab.hkc3a2cwlrvr4neer-f4wz8o_vv3t4gp1btj8ys5c3w47ju1hbpyl4klui5gfq95r1-_aq3rc2lhduxu;odgycp.-e0v7bk7th327d49ws5yim+j3kfbc3borgm40aa1j0mv2n4ftm1ybdicefjldp6.cjkwdrd19x;3ec6du4+-jhfk3n-4rl5+z5+p5iy93g8sq_tlhgeeuso8-gxxhjz0d7z+14sn4b440ov',
                replication = None,
                tag_style = None,
                u2f = None,
                user_tag_access = None,
                webauthn = None
            )
        else:
            return ClusterOptionsSetOptionsRequest(
        )
        """

    def testClusterOptionsSetOptionsRequest(self):
        """Test ClusterOptionsSetOptionsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
