# coding: utf-8

"""
    Proxmox Virtual Environment API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 8.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pve_client.models.cluster_mapping_create_usb_request_map_inner_one_of import ClusterMappingCreateUsbRequestMapInnerOneOf

class TestClusterMappingCreateUsbRequestMapInnerOneOf(unittest.TestCase):
    """ClusterMappingCreateUsbRequestMapInnerOneOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClusterMappingCreateUsbRequestMapInnerOneOf:
        """Test ClusterMappingCreateUsbRequestMapInnerOneOf
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClusterMappingCreateUsbRequestMapInnerOneOf`
        """
        model = ClusterMappingCreateUsbRequestMapInnerOneOf()
        if include_optional:
            return ClusterMappingCreateUsbRequestMapInnerOneOf(
                description = '',
                id = ERROR_TO_EXAMPLE_VALUE,
                node = 'gWzyBAw2ZuufUOHOEhA8IcFQXnuaZcdyyvKX7HzKpul80FcVjSkp5IHYCm6w-v0dZfU7',
                path = ERROR_TO_EXAMPLE_VALUE
            )
        else:
            return ClusterMappingCreateUsbRequestMapInnerOneOf(
                id = ERROR_TO_EXAMPLE_VALUE,
                node = 'gWzyBAw2ZuufUOHOEhA8IcFQXnuaZcdyyvKX7HzKpul80FcVjSkp5IHYCm6w-v0dZfU7',
        )
        """

    def testClusterMappingCreateUsbRequestMapInnerOneOf(self):
        """Test ClusterMappingCreateUsbRequestMapInnerOneOf"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
