# coding: utf-8

"""
    Proxmox Virtual Environment API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 8.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pve_client.models.cluster_notifications_create_webhook_endpoint_request import ClusterNotificationsCreateWebhookEndpointRequest

class TestClusterNotificationsCreateWebhookEndpointRequest(unittest.TestCase):
    """ClusterNotificationsCreateWebhookEndpointRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClusterNotificationsCreateWebhookEndpointRequest:
        """Test ClusterNotificationsCreateWebhookEndpointRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClusterNotificationsCreateWebhookEndpointRequest`
        """
        model = ClusterNotificationsCreateWebhookEndpointRequest()
        if include_optional:
            return ClusterNotificationsCreateWebhookEndpointRequest(
                body = '',
                comment = '',
                disable = 0,
                header = [
                    ''
                    ],
                method = 'post',
                name = 'AqXzyCBw3_uufVPIPFhB9JcGRYnua',
                secret = [
                    ''
                    ],
                url = ''
            )
        else:
            return ClusterNotificationsCreateWebhookEndpointRequest(
                method = 'post',
                name = 'AqXzyCBw3_uufVPIPFhB9JcGRYnua',
                url = '',
        )
        """

    def testClusterNotificationsCreateWebhookEndpointRequest(self):
        """Test ClusterNotificationsCreateWebhookEndpointRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
