# coding: utf-8

"""
    Proxmox Virtual Environment API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 8.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pve_client.api.cluster_config_api import ClusterConfigApi


class TestClusterConfigApi(unittest.TestCase):
    """ClusterConfigApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ClusterConfigApi()

    def tearDown(self) -> None:
        pass

    def test_addnode(self) -> None:
        """Test case for addnode

        Adds a node to the cluster configuration
        """
        pass

    def test_create_config(self) -> None:
        """Test case for create_config

        Generate new cluster configuration
        """
        pass

    def test_delnode(self) -> None:
        """Test case for delnode

        Removes a node from the cluster configuration
        """
        pass

    def test_get_config(self) -> None:
        """Test case for get_config

        Directory index
        """
        pass

    def test_join(self) -> None:
        """Test case for join

        Joins this node into an existing cluster
        """
        pass

    def test_join_api_version(self) -> None:
        """Test case for join_api_version

        Return the version of the cluster join API available on this node
        """
        pass

    def test_join_info(self) -> None:
        """Test case for join_info

        Get information needed to join this cluster over the connected node
        """
        pass

    def test_nodes(self) -> None:
        """Test case for nodes

        Corosync node list
        """
        pass

    def test_status(self) -> None:
        """Test case for status

        Get QDevice status
        """
        pass

    def test_totem(self) -> None:
        """Test case for totem

        Get corosync totem protocol settings
        """
        pass


if __name__ == '__main__':
    unittest.main()
