# coding: utf-8

"""
    Proxmox Virtual Environment API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 8.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pve_client.models.pve_influxdbproto_enum import PveInfluxdbprotoEnum

class TestPveInfluxdbprotoEnum(unittest.TestCase):
    """PveInfluxdbprotoEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPveInfluxdbprotoEnum(self):
        """Test PveInfluxdbprotoEnum"""
        # inst = PveInfluxdbprotoEnum()

if __name__ == '__main__':
    unittest.main()
