# coding: utf-8

"""
    Proxmox Virtual Environment API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 8.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pve_client.models.cluster_config_join_request import ClusterConfigJoinRequest

class TestClusterConfigJoinRequest(unittest.TestCase):
    """ClusterConfigJoinRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClusterConfigJoinRequest:
        """Test ClusterConfigJoinRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClusterConfigJoinRequest`
        """
        model = ClusterConfigJoinRequest()
        if include_optional:
            return ClusterConfigJoinRequest(
                fingerprint = '62:EC:B0:20:84:29:30:cc:01:FF:CC:fe:Ee:15:0A:C3:2D:cA:Ec:8a:83:DD:D7:dB:F7:56:7C:88:19:5f:fc:ea',
                force = 0,
                hostname = '',
                link0 = None,
                link1 = None,
                link2 = None,
                link3 = None,
                link4 = None,
                link5 = None,
                link6 = None,
                link7 = None,
                nodeid = 1,
                password = '',
                votes = 0
            )
        else:
            return ClusterConfigJoinRequest(
                fingerprint = '62:EC:B0:20:84:29:30:cc:01:FF:CC:fe:Ee:15:0A:C3:2D:cA:Ec:8a:83:DD:D7:dB:F7:56:7C:88:19:5f:fc:ea',
                hostname = '',
                password = '',
        )
        """

    def testClusterConfigJoinRequest(self):
        """Test ClusterConfigJoinRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
