# coding: utf-8

"""
    Proxmox Virtual Environment API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 8.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pve_client.models.cluster_firewall_get_rules_get_rules_response import ClusterFirewallGetRulesGetRulesResponse

class TestClusterFirewallGetRulesGetRulesResponse(unittest.TestCase):
    """ClusterFirewallGetRulesGetRulesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClusterFirewallGetRulesGetRulesResponse:
        """Test ClusterFirewallGetRulesGetRulesResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClusterFirewallGetRulesGetRulesResponse`
        """
        model = ClusterFirewallGetRulesGetRulesResponse()
        if include_optional:
            return ClusterFirewallGetRulesGetRulesResponse(
                data = [
                    pve_client.models.cluster_firewall_get_rules_response_data_inner.ClusterFirewallGetRulesResponse_data_inner(
                        action = '', 
                        comment = '', 
                        dest = '', 
                        dport = '', 
                        enable = 56, 
                        icmp_type = '', 
                        iface = '', 
                        ipversion = 56, 
                        log = null, 
                        macro = '', 
                        pos = 56, 
                        proto = '', 
                        source = '', 
                        sport = '', 
                        type = '', )
                    ],
                total = 56,
                changes = None
            )
        else:
            return ClusterFirewallGetRulesGetRulesResponse(
                data = [
                    pve_client.models.cluster_firewall_get_rules_response_data_inner.ClusterFirewallGetRulesResponse_data_inner(
                        action = '', 
                        comment = '', 
                        dest = '', 
                        dport = '', 
                        enable = 56, 
                        icmp_type = '', 
                        iface = '', 
                        ipversion = 56, 
                        log = null, 
                        macro = '', 
                        pos = 56, 
                        proto = '', 
                        source = '', 
                        sport = '', 
                        type = '', )
                    ],
        )
        """

    def testClusterFirewallGetRulesGetRulesResponse(self):
        """Test ClusterFirewallGetRulesGetRulesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
