# coding: utf-8

"""
    Proxmox Virtual Environment API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 8.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pve_client.models.cluster_sdn_get_vnets_response_data_inner_pending import ClusterSdnGetVnetsResponseDataInnerPending

class TestClusterSdnGetVnetsResponseDataInnerPending(unittest.TestCase):
    """ClusterSdnGetVnetsResponseDataInnerPending unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClusterSdnGetVnetsResponseDataInnerPending:
        """Test ClusterSdnGetVnetsResponseDataInnerPending
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClusterSdnGetVnetsResponseDataInnerPending`
        """
        model = ClusterSdnGetVnetsResponseDataInnerPending()
        if include_optional:
            return ClusterSdnGetVnetsResponseDataInnerPending(
                alias = 'g0q-N:NmRgWQ JJ8fGtZ.zc\\cf e,Zg[JX\\J*umQE[[UxCG)=kl.*V WSM7JL^ D _lKDCqU@rs^JG \\oPVp<UM6rTbQxBJ]1GAj SYcWV+e<\\k\\H FO+JNEM w@x]qtV/ ))_GDRm)>QtR?<] l[jJWW^Fqlw Y:s:p(gkZ-je*,\\adJeE/j>M/,',
                isolate_ports = 0,
                tag = 1,
                vlanaware = 0,
                zone = ''
            )
        else:
            return ClusterSdnGetVnetsResponseDataInnerPending(
        )
        """

    def testClusterSdnGetVnetsResponseDataInnerPending(self):
        """Test ClusterSdnGetVnetsResponseDataInnerPending"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
