# coding: utf-8

"""
    Proxmox Virtual Environment API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 8.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pve_client.models.cluster_notifications_get_sendmail_endpoint_response_data import ClusterNotificationsGetSendmailEndpointResponseData

class TestClusterNotificationsGetSendmailEndpointResponseData(unittest.TestCase):
    """ClusterNotificationsGetSendmailEndpointResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClusterNotificationsGetSendmailEndpointResponseData:
        """Test ClusterNotificationsGetSendmailEndpointResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClusterNotificationsGetSendmailEndpointResponseData`
        """
        model = ClusterNotificationsGetSendmailEndpointResponseData()
        if include_optional:
            return ClusterNotificationsGetSendmailEndpointResponseData(
                author = '',
                comment = '',
                digest = '',
                disable = 0,
                from_address = '',
                mailto = [
                    'EbUUGjjNSwg0_bs9ZayIMrKdgNvb6gvxmPb9GcsM61ate1RA89q3w1l4eH4XxEz.5aw'
                    ],
                mailto_user = [
                    'W@iUUGjjNSwg0_bs9ZayIMrKdgNvb6gvxmPb9GcsM61ate1RA89q3w1l4eH4XxEz.5awxoFZxH'
                    ],
                name = 'AqXzyCBw3_uufVPIPFhB9JcGRYnua'
            )
        else:
            return ClusterNotificationsGetSendmailEndpointResponseData(
                name = 'AqXzyCBw3_uufVPIPFhB9JcGRYnua',
        )
        """

    def testClusterNotificationsGetSendmailEndpointResponseData(self):
        """Test ClusterNotificationsGetSendmailEndpointResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
