# coding: utf-8

"""
    Proxmox Virtual Environment API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 8.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pve_client.models.cluster_acme_register_account_request import ClusterAcmeRegisterAccountRequest

class TestClusterAcmeRegisterAccountRequest(unittest.TestCase):
    """ClusterAcmeRegisterAccountRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClusterAcmeRegisterAccountRequest:
        """Test ClusterAcmeRegisterAccountRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClusterAcmeRegisterAccountRequest`
        """
        model = ClusterAcmeRegisterAccountRequest()
        if include_optional:
            return ClusterAcmeRegisterAccountRequest(
                contact = '',
                directory = 'https://acme-v02.api.letsencrypt.org/directory',
                eab_hmac_key = '',
                eab_kid = '',
                name = 'default',
                tos_url = ''
            )
        else:
            return ClusterAcmeRegisterAccountRequest(
                contact = '',
        )
        """

    def testClusterAcmeRegisterAccountRequest(self):
        """Test ClusterAcmeRegisterAccountRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
