# coding: utf-8

"""
    Proxmox Virtual Environment API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 8.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pve_client.models.pve_sdn_ipam_phpipam_config import PveSdnIpamPhpipamConfig

class TestPveSdnIpamPhpipamConfig(unittest.TestCase):
    """PveSdnIpamPhpipamConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PveSdnIpamPhpipamConfig:
        """Test PveSdnIpamPhpipamConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PveSdnIpamPhpipamConfig`
        """
        model = PveSdnIpamPhpipamConfig()
        if include_optional:
            return PveSdnIpamPhpipamConfig(
                url = '',
                token = '',
                section = 56,
                fingerprint = '62:EC:B0:20:84:29:30:cc:01:FF:CC:fe:Ee:15:0A:C3:2D:cA:Ec:8a:83:DD:D7:dB:F7:56:7C:88:19:5f:fc:ea',
                type = 'phpipam'
            )
        else:
            return PveSdnIpamPhpipamConfig(
                url = '',
                token = '',
                section = 56,
                type = 'phpipam',
        )
        """

    def testPveSdnIpamPhpipamConfig(self):
        """Test PveSdnIpamPhpipamConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
