# coding: utf-8

"""
    Proxmox Virtual Environment API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 8.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pve_client.models.pve_cluster_sdn_inline_enum import PveClusterSdnInlineEnum

class TestPveClusterSdnInlineEnum(unittest.TestCase):
    """PveClusterSdnInlineEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPveClusterSdnInlineEnum(self):
        """Test PveClusterSdnInlineEnum"""
        # inst = PveClusterSdnInlineEnum()

if __name__ == '__main__':
    unittest.main()
