# coding: utf-8

"""
    Proxmox Virtual Environment API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 8.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pve_client.models.cluster_metrics_export_response import ClusterMetricsExportResponse

class TestClusterMetricsExportResponse(unittest.TestCase):
    """ClusterMetricsExportResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClusterMetricsExportResponse:
        """Test ClusterMetricsExportResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClusterMetricsExportResponse`
        """
        model = ClusterMetricsExportResponse()
        if include_optional:
            return ClusterMetricsExportResponse(
                data = pve_client.models.cluster_metrics_export_response_data.ClusterMetricsExportResponse_data(
                    data = [
                        pve_client.models.cluster_metrics_export_response_data_data_inner.ClusterMetricsExportResponse_data_data_inner(
                            id = '', 
                            metric = '', 
                            timestamp = 56, 
                            type = null, 
                            value = 1.337, )
                        ], ),
                total = 56,
                changes = None
            )
        else:
            return ClusterMetricsExportResponse(
                data = pve_client.models.cluster_metrics_export_response_data.ClusterMetricsExportResponse_data(
                    data = [
                        pve_client.models.cluster_metrics_export_response_data_data_inner.ClusterMetricsExportResponse_data_data_inner(
                            id = '', 
                            metric = '', 
                            timestamp = 56, 
                            type = null, 
                            value = 1.337, )
                        ], ),
        )
        """

    def testClusterMetricsExportResponse(self):
        """Test ClusterMetricsExportResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
