# coding: utf-8

"""
    Proxmox Virtual Environment API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 8.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pve_client.models.nodes_ceph_lspools_response import NodesCephLspoolsResponse

class TestNodesCephLspoolsResponse(unittest.TestCase):
    """NodesCephLspoolsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NodesCephLspoolsResponse:
        """Test NodesCephLspoolsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NodesCephLspoolsResponse`
        """
        model = NodesCephLspoolsResponse()
        if include_optional:
            return NodesCephLspoolsResponse(
                data = [
                    pve_client.models.nodes_ceph_lspools_response_data_inner.NodesCephLspoolsResponse_data_inner(
                        application_metadata = pve_client.models.associated_applications.Associated Applications(), 
                        autoscale_status = pve_client.models.autoscale_status.Autoscale Status(), 
                        bytes_used = 56, 
                        crush_rule = 56, 
                        crush_rule_name = '', 
                        min_size = 56, 
                        percent_used = 1.337, 
                        pg_autoscale_mode = '', 
                        pg_num = 56, 
                        pg_num_final = 56, 
                        pg_num_min = 56, 
                        pool = 56, 
                        pool_name = '', 
                        size = 56, 
                        target_size = 56, 
                        target_size_ratio = 1.337, 
                        type = null, )
                    ],
                total = 56,
                changes = None
            )
        else:
            return NodesCephLspoolsResponse(
                data = [
                    pve_client.models.nodes_ceph_lspools_response_data_inner.NodesCephLspoolsResponse_data_inner(
                        application_metadata = pve_client.models.associated_applications.Associated Applications(), 
                        autoscale_status = pve_client.models.autoscale_status.Autoscale Status(), 
                        bytes_used = 56, 
                        crush_rule = 56, 
                        crush_rule_name = '', 
                        min_size = 56, 
                        percent_used = 1.337, 
                        pg_autoscale_mode = '', 
                        pg_num = 56, 
                        pg_num_final = 56, 
                        pg_num_min = 56, 
                        pool = 56, 
                        pool_name = '', 
                        size = 56, 
                        target_size = 56, 
                        target_size_ratio = 1.337, 
                        type = null, )
                    ],
        )
        """

    def testNodesCephLspoolsResponse(self):
        """Test NodesCephLspoolsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
