# coding: utf-8

"""
    Proxmox Virtual Environment API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 8.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pve_client.models.pools_read_pool_response_data import PoolsReadPoolResponseData

class TestPoolsReadPoolResponseData(unittest.TestCase):
    """PoolsReadPoolResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PoolsReadPoolResponseData:
        """Test PoolsReadPoolResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PoolsReadPoolResponseData`
        """
        model = PoolsReadPoolResponseData()
        if include_optional:
            return PoolsReadPoolResponseData(
                comment = '',
                members = [
                    pve_client.models.pools_get_pools_response_data_inner_members_inner.PoolsGetPoolsResponse_data_inner_members_inner(
                        id = '', 
                        node = '', 
                        storage = '', 
                        type = 'qemu', 
                        vmid = 56, )
                    ]
            )
        else:
            return PoolsReadPoolResponseData(
                members = [
                    pve_client.models.pools_get_pools_response_data_inner_members_inner.PoolsGetPoolsResponse_data_inner_members_inner(
                        id = '', 
                        node = '', 
                        storage = '', 
                        type = 'qemu', 
                        vmid = 56, )
                    ],
        )
        """

    def testPoolsReadPoolResponseData(self):
        """Test PoolsReadPoolResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
