# coding: utf-8

"""
    Proxmox Virtual Environment API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 8.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pve_client.models.nodes_status_status_response_data import NodesStatusStatusResponseData

class TestNodesStatusStatusResponseData(unittest.TestCase):
    """NodesStatusStatusResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NodesStatusStatusResponseData:
        """Test NodesStatusStatusResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NodesStatusStatusResponseData`
        """
        model = NodesStatusStatusResponseData()
        if include_optional:
            return NodesStatusStatusResponseData(
                boot_info = pve_client.models.nodes_status_status_response_data_boot_info.NodesStatusStatusResponse_data_boot_info(
                    mode = null, 
                    secureboot = null, ),
                cpu = 1.337,
                cpuinfo = pve_client.models.nodes_status_status_response_data_cpuinfo.NodesStatusStatusResponse_data_cpuinfo(
                    cores = 56, 
                    cpus = 56, 
                    model = '', 
                    sockets = 56, ),
                current_kernel = pve_client.models.nodes_status_status_response_data_current_kernel.NodesStatusStatusResponse_data_current_kernel(
                    machine = '', 
                    release = '', 
                    sysname = '', 
                    version = '', ),
                loadavg = [
                    ''
                    ],
                memory = pve_client.models.nodes_status_status_response_data_memory.NodesStatusStatusResponse_data_memory(
                    available = 56, 
                    free = 56, 
                    total = 56, 
                    used = 56, ),
                pveversion = '',
                rootfs = pve_client.models.nodes_status_status_response_data_rootfs.NodesStatusStatusResponse_data_rootfs(
                    avail = 56, 
                    free = 56, 
                    total = 56, 
                    used = 56, )
            )
        else:
            return NodesStatusStatusResponseData(
                boot_info = pve_client.models.nodes_status_status_response_data_boot_info.NodesStatusStatusResponse_data_boot_info(
                    mode = null, 
                    secureboot = null, ),
                cpu = 1.337,
                cpuinfo = pve_client.models.nodes_status_status_response_data_cpuinfo.NodesStatusStatusResponse_data_cpuinfo(
                    cores = 56, 
                    cpus = 56, 
                    model = '', 
                    sockets = 56, ),
                current_kernel = pve_client.models.nodes_status_status_response_data_current_kernel.NodesStatusStatusResponse_data_current_kernel(
                    machine = '', 
                    release = '', 
                    sysname = '', 
                    version = '', ),
                loadavg = [
                    ''
                    ],
                memory = pve_client.models.nodes_status_status_response_data_memory.NodesStatusStatusResponse_data_memory(
                    available = 56, 
                    free = 56, 
                    total = 56, 
                    used = 56, ),
                pveversion = '',
                rootfs = pve_client.models.nodes_status_status_response_data_rootfs.NodesStatusStatusResponse_data_rootfs(
                    avail = 56, 
                    free = 56, 
                    total = 56, 
                    used = 56, ),
        )
        """

    def testNodesStatusStatusResponseData(self):
        """Test NodesStatusStatusResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
