# coding: utf-8

"""
    Proxmox Virtual Environment API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 9.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from clientapi_pve.models.pve_boolean import PveBoolean
from clientapi_pve.models.pve_dhcp_enum import PveDhcpEnum
from clientapi_pve.models.pve_vlan_protocol_enum import PveVlanProtocolEnum
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ClusterSdnGetZonesResponseDataInnerPending(BaseModel):
    """
    Changes that have not yet been applied to the running configuration.
    """ # noqa: E501

    advertise_subnets: Optional[PveBoolean] = Field(default=None, description="Advertise IP prefixes (Type-5 routes) instead of MAC/IP pairs (Type-2 routes). EVPN zone only.", alias="advertise-subnets")

    bridge: Optional[StrictStr] = Field(default=None, description="the bridge for which VLANs should be managed. VLAN & QinQ zone only.")

    bridge_disable_mac_learning: Optional[PveBoolean] = Field(default=None, description="Disable auto mac learning. VLAN zone only.", alias="bridge-disable-mac-learning")

    controller: Optional[StrictStr] = Field(default=None, description="ID of the controller for this zone. EVPN zone only.")

    dhcp: Optional[PveDhcpEnum] = Field(default=None, description="Name of DHCP server backend for this zone.")

    disable_arp_nd_suppression: Optional[PveBoolean] = Field(default=None, description="Suppress IPv4 ARP && IPv6 Neighbour Discovery messages. EVPN zone only.", alias="disable-arp-nd-suppression")

    dns: Optional[StrictStr] = Field(default=None, description="ID of the DNS server for this zone.")

    dnszone: Optional[StrictStr] = Field(default=None, description="Domain name for this zone.")

    exitnodes: Optional[StrictStr] = Field(default=None, description="List of PVE Nodes that should act as exit node for this zone. EVPN zone only.")

    exitnodes_local_routing: Optional[PveBoolean] = Field(default=None, description="Create routes on the exit nodes, so they can connect to EVPN guests. EVPN zone only.", alias="exitnodes-local-routing")

    exitnodes_primary: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Force traffic through this exitnode first. EVPN zone only.", alias="exitnodes-primary")

    ipam: Optional[StrictStr] = Field(default=None, description="ID of the IPAM for this zone.")

    mac: Optional[StrictStr] = Field(default=None, description="MAC address of the anycast router for this zone.")

    mtu: Optional[StrictInt] = Field(default=None, description="MTU of the zone, will be used for the created VNet bridges.")

    nodes: Optional[StrictStr] = Field(default=None, description="Nodes where this zone should be created.")

    peers: Optional[StrictStr] = Field(default=None, description="Comma-separated list of peers, that are part of the VXLAN zone. Usually the IPs of the nodes. VXLAN zone only.")

    reversedns: Optional[StrictStr] = Field(default=None, description="ID of the reverse DNS server for this zone.")

    rt_import: Optional[StrictStr] = Field(default=None, description="Route-Targets that should be imported into the VRF of this zone via BGP. EVPN zone only.", alias="rt-import")

    secondary_controllers: Optional[List[Annotated[str, Field(min_length=2, strict=True, max_length=64)]]] = Field(default=None, description="Additional controllers.", alias="secondary-controllers")

    tag: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Service-VLAN Tag (outer VLAN). QinQ zone only")

    vlan_protocol: Optional[PveVlanProtocolEnum] = Field(default=None, description="VLAN protocol for the creation of the QinQ zone. QinQ zone only.", alias="vlan-protocol")

    vrf_vxlan: Optional[Annotated[int, Field(le=16777215, strict=True, ge=1)]] = Field(default=None, description="VNI for the zone VRF. EVPN zone only.", alias="vrf-vxlan")

    vxlan_port: Optional[Annotated[int, Field(le=65536, strict=True, ge=1)]] = Field(default=4789, description="UDP port that should be used for the VXLAN tunnel (default 4789). VXLAN zone only.", alias="vxlan-port")

    __properties: ClassVar[List[str]] = ["advertise-subnets", "bridge", "bridge-disable-mac-learning", "controller", "dhcp", "disable-arp-nd-suppression", "dns", "dnszone", "exitnodes", "exitnodes-local-routing", "exitnodes-primary", "ipam", "mac", "mtu", "nodes", "peers", "reversedns", "rt-import", "secondary-controllers", "tag", "vlan-protocol", "vrf-vxlan", "vxlan-port"]












    @field_validator('exitnodes_primary')
    def exitnodes_primary_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^(?:[a-zA-Z0-9](?:[a-zA-Z0-9\-]*[a-zA-Z0-9])?)$", value):
            raise ValueError(r"must validate the regular expression /^(?:[a-zA-Z0-9](?:[a-zA-Z0-9\-]*[a-zA-Z0-9])?)$/")
        return value















    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ClusterSdnGetZonesResponseDataInnerPending from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            # `exclude_unset` keeps schema defaults out of the wire payload
            # when the user constructed the model directly (e.g.
            # `Req(vmid=100)` would otherwise pull in
            # `cores=1, cpulimit=0, …` from the spec defaults and PVE
            # rejects the request with 400 because it never set those).
            # `exclude_none` keeps None values out of the wire payload —
            # both for direct construction (None means "unset") and for
            # the from_dict path (where unspecified obj keys become
            # `obj.get("k") == None` but show up in `model_fields_set`).
            exclude_unset=True,
            exclude_none=True,
        )
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ClusterSdnGetZonesResponseDataInnerPending from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "advertise-subnets": obj.get("advertise-subnets"),
            "bridge": obj.get("bridge"),
            "bridge-disable-mac-learning": obj.get("bridge-disable-mac-learning"),
            "controller": obj.get("controller"),
            "dhcp": obj.get("dhcp"),
            "disable-arp-nd-suppression": obj.get("disable-arp-nd-suppression"),
            "dns": obj.get("dns"),
            "dnszone": obj.get("dnszone"),
            "exitnodes": obj.get("exitnodes"),
            "exitnodes-local-routing": obj.get("exitnodes-local-routing"),
            "exitnodes-primary": obj.get("exitnodes-primary"),
            "ipam": obj.get("ipam"),
            "mac": obj.get("mac"),
            "mtu": obj.get("mtu"),
            "nodes": obj.get("nodes"),
            "peers": obj.get("peers"),
            "reversedns": obj.get("reversedns"),
            "rt-import": obj.get("rt-import"),
            "secondary-controllers": obj.get("secondary-controllers"),
            "tag": obj.get("tag"),
            "vlan-protocol": obj.get("vlan-protocol"),
            "vrf-vxlan": obj.get("vrf-vxlan"),
            "vxlan-port": obj.get("vxlan-port") if obj.get("vxlan-port") is not None else 4789
        })
        return _obj


