# coding: utf-8

"""
    Proxmox Virtual Environment API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 9.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PveCacheEnum(str, Enum):
    """
    PveCacheEnum
    """

    """
    allowed enum values
    """
    NONE = 'none'
    WRITETHROUGH = 'writethrough'
    WRITEBACK = 'writeback'
    UNSAFE = 'unsafe'
    DIRECTSYNC = 'directsync'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PveCacheEnum from a JSON string"""
        return cls(json.loads(json_str))


