# coding: utf-8

"""
    Proxmox Virtual Environment API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 9.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from clientapi_pve.models.pve_key_enum import PveKeyEnum
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PveExitActionConfig(BaseModel):
    """
    PveExitActionConfig
    """ # noqa: E501

    key: PveKeyEnum

    value: Optional[Annotated[int, Field(le=65535, strict=True, ge=0)]] = Field(default=None, description="The index of this route map entry")

    __properties: ClassVar[List[str]] = ["key", "value"]





    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PveExitActionConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PveExitActionConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "key": obj.get("key"),
            "value": obj.get("value")
        })
        return _obj


    def to_shorthand(self) -> str:
        """Serialise this PveExitActionConfig into Proxmox's CLI-style shorthand
        string (``key=value,…``).

        The property marked ``x-pve-default-key`` is emitted positionally
        without a ``key=`` prefix; aliases collapse multiple property
        names to the same wire key.

        Example::

            >>> PveExitActionConfig(model='virtio', bridge='vmbr0', firewall=1).to_shorthand()
            'virtio,bridge=vmbr0,firewall=1'
        """
        parts: list[str] = []
        
        
        if self.key is not None:
            parts.append(f"key={self.key}")
        
        if self.value is not None:
            parts.append(f"value={self.value}")
        
        return ",".join(parts)

    @classmethod
    def from_shorthand(cls, raw: Optional[str]) -> Optional["PveExitActionConfig"]:
        """Parse a Proxmox shorthand string into a PveExitActionConfig. Mirror of
        :meth:`to_shorthand`. The first comma-separated segment without
        ``=`` is interpreted as the default-key value.
        """
        if raw is None:
            return None
        kwargs: dict = {}
        default_key_consumed = False
        for part in raw.split(","):
            if not part:
                continue
            if "=" not in part:
                
                continue
            k, _, v = part.partition("=")
            kwargs[k.replace("-", "_")] = v
        return cls(**kwargs)

