# coding: utf-8

"""
    Proxmox Virtual Environment API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 9.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from clientapi_pve.models.pve_boolean import PveBoolean
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PveRealmOpenidConfig(BaseModel):
    """
    PveRealmOpenidConfig
    """ # noqa: E501

    audiences: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="A list of audiences that the OpenID Issuer may include that are accepted in addition to 'client-id'.")

    check_connection: Optional[PveBoolean] = Field(default=None, description="Check bind connection to the server.", alias="check-connection")

    realm: Annotated[str, Field(strict=True, max_length=32)] = Field(description="Authentication domain ID")

    issuer_url: Annotated[str, Field(strict=True, max_length=256)] = Field(description="OpenID Issuer Url", alias="issuer-url")

    client_id: Annotated[str, Field(strict=True, max_length=256)] = Field(description="OpenID Client ID", alias="client-id")

    client_key: Optional[Annotated[str, Field(strict=True, max_length=256)]] = Field(default=None, description="OpenID Client Key", alias="client-key")

    autocreate: Optional[PveBoolean] = Field(default=None, description="Automatically create users if they do not exist.")

    username_claim: Optional[StrictStr] = Field(default=None, description="OpenID claim used to generate the unique username.", alias="username-claim")

    groups_claim: Optional[Annotated[str, Field(strict=True, max_length=256)]] = Field(default=None, description="OpenID claim used to retrieve groups with.", alias="groups-claim")

    groups_autocreate: Optional[PveBoolean] = Field(default=None, description="Automatically create groups if they do not exist.", alias="groups-autocreate")

    groups_overwrite: Optional[PveBoolean] = Field(default=None, description="All groups will be overwritten for the user on login.", alias="groups-overwrite")

    prompt: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Specifies whether the Authorization Server prompts the End-User for reauthentication and consent.")

    scopes: Optional[StrictStr] = Field(default='email profile', description="Specifies the scopes (user details) that should be authorized and returned, for example 'email' or 'profile'.")

    acr_values: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Specifies the Authentication Context Class Reference values that theAuthorization Server is being requested to use for the Auth Request.", alias="acr-values")

    default: Optional[PveBoolean] = Field(default=None, description="Use this as default realm")

    comment: Optional[Annotated[str, Field(strict=True, max_length=4096)]] = Field(default=None, description="Description.")

    query_userinfo: Optional[PveBoolean] = Field(default=None, description="Enables querying the userinfo endpoint for claims values.", alias="query-userinfo")

    type: StrictStr

    __properties: ClassVar[List[str]] = ["audiences", "check-connection", "realm", "issuer-url", "client-id", "client-key", "autocreate", "username-claim", "groups-claim", "groups-autocreate", "groups-overwrite", "prompt", "scopes", "acr-values", "default", "comment", "query-userinfo", "type"]


    @field_validator('audiences')
    def audiences_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[^\x00-\x1F\x7F <>#\u0022]*$", value):
            raise ValueError(r"must validate the regular expression /^[^\x00-\x1F\x7F <>#\u0022]*$/")
        return value



    @field_validator('realm')
    def realm_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z][A-Za-z0-9.\-_]+$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z][A-Za-z0-9.\-_]+$/")
        return value







    @field_validator('groups_claim')
    def groups_claim_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"(?:[A-Za-z0-9\.\-_]+)", value):
            raise ValueError(r"must validate the regular expression /(?:[A-Za-z0-9\.\-_]+)/")
        return value




    @field_validator('prompt')
    def prompt_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"(?:none|login|consent|select_account|\S+)", value):
            raise ValueError(r"must validate the regular expression /(?:none|login|consent|select_account|\S+)/")
        return value



    @field_validator('acr_values')
    def acr_values_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[^\x00-\x1F\x7F <>#\u0022]*$", value):
            raise ValueError(r"must validate the regular expression /^[^\x00-\x1F\x7F <>#\u0022]*$/")
        return value





    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['openid']):
            raise ValueError("must be one of enum values ('openid')")
        return value



    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PveRealmOpenidConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            # `exclude_unset` keeps schema defaults out of the wire payload
            # when the user constructed the model directly (e.g.
            # `Req(vmid=100)` would otherwise pull in
            # `cores=1, cpulimit=0, …` from the spec defaults and PVE
            # rejects the request with 400 because it never set those).
            # `exclude_none` keeps None values out of the wire payload —
            # both for direct construction (None means "unset") and for
            # the from_dict path (where unspecified obj keys become
            # `obj.get("k") == None` but show up in `model_fields_set`).
            exclude_unset=True,
            exclude_none=True,
        )
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PveRealmOpenidConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "audiences": obj.get("audiences"),
            "check-connection": obj.get("check-connection"),
            "realm": obj.get("realm"),
            "issuer-url": obj.get("issuer-url"),
            "client-id": obj.get("client-id"),
            "client-key": obj.get("client-key"),
            "autocreate": obj.get("autocreate"),
            "username-claim": obj.get("username-claim"),
            "groups-claim": obj.get("groups-claim"),
            "groups-autocreate": obj.get("groups-autocreate"),
            "groups-overwrite": obj.get("groups-overwrite"),
            "prompt": obj.get("prompt"),
            "scopes": obj.get("scopes") if obj.get("scopes") is not None else 'email profile',
            "acr-values": obj.get("acr-values"),
            "default": obj.get("default"),
            "comment": obj.get("comment"),
            "query-userinfo": obj.get("query-userinfo"),
            "type": obj.get("type")
        })
        return _obj


