# coding: utf-8

"""
    Proxmox Virtual Environment API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 9.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PveMetaConfig(BaseModel):
    """
    PveMetaConfig
    """ # noqa: E501

    creation_qemu: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="The QEMU (machine) version from the time this VM was created.", alias="creation-qemu")

    ctime: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="The guest creation timestamp as UNIX epoch time")

    __properties: ClassVar[List[str]] = ["creation-qemu", "ctime"]


    @field_validator('creation_qemu')
    def creation_qemu_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"\d+(\.\d+)+", value):
            raise ValueError(r"must validate the regular expression /\d+(\.\d+)+/")
        return value




    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PveMetaConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            # `exclude_unset` keeps schema defaults out of the wire payload
            # when the user constructed the model directly (e.g.
            # `Req(vmid=100)` would otherwise pull in
            # `cores=1, cpulimit=0, …` from the spec defaults and PVE
            # rejects the request with 400 because it never set those).
            # `exclude_none` keeps None values out of the wire payload —
            # both for direct construction (None means "unset") and for
            # the from_dict path (where unspecified obj keys become
            # `obj.get("k") == None` but show up in `model_fields_set`).
            exclude_unset=True,
            exclude_none=True,
        )
        
        
        
        
        
        
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PveMetaConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "creation-qemu": obj.get("creation-qemu"),
            "ctime": obj.get("ctime")
        })
        return _obj


    def to_shorthand(self) -> str:
        """Serialise this PveMetaConfig into Proxmox's CLI-style shorthand
        string (``key=value,…``).

        The property marked ``x-pve-default-key`` is emitted positionally
        without a ``key=`` prefix; aliases collapse multiple property
        names to the same wire key.

        Example::

            >>> PveMetaConfig(model='virtio', bridge='vmbr0', firewall=1).to_shorthand()
            'virtio,bridge=vmbr0,firewall=1'
        """
        parts: list[str] = []
        
        
        if self.creation_qemu is not None:
            parts.append(f"creation-qemu={self.creation_qemu}")
        
        if self.ctime is not None:
            parts.append(f"ctime={self.ctime}")
        
        return ",".join(parts)

    @classmethod
    def from_shorthand(cls, raw: Optional[str]) -> Optional["PveMetaConfig"]:
        """Parse a Proxmox shorthand string into a PveMetaConfig. Mirror of
        :meth:`to_shorthand`. The first comma-separated segment without
        ``=`` is interpreted as the default-key value.
        """
        if raw is None:
            return None
        kwargs: dict = {}
        default_key_consumed = False
        for part in raw.split(","):
            if not part:
                continue
            if "=" not in part:
                
                continue
            k, _, v = part.partition("=")
            kwargs[k.replace("-", "_")] = v
        return cls(**kwargs)

