# coding: utf-8

"""
    Proxmox Virtual Environment API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 8.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from pve_client.models.pve_type_enum import PveTypeEnum
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AccessTfaAddTfaEntryRequest(BaseModel):
    """
    AccessTfaAddTfaEntryRequest
    """ # noqa: E501

    challenge: Optional[StrictStr] = Field(default=None, description="When responding to a u2f challenge: the original challenge string")

    description: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="A description to distinguish multiple entries from one another")

    password: Optional[Annotated[str, Field(min_length=5, strict=True, max_length=64)]] = Field(default=None, description="The current password of the user performing the change.")

    totp: Optional[StrictStr] = Field(default=None, description="A totp URI.")

    type: PveTypeEnum = Field(description="TFA Entry Type.")

    value: Optional[StrictStr] = Field(default=None, description="The current value for the provided totp URI, or a Webauthn/U2F challenge response")

    __properties: ClassVar[List[str]] = ["challenge", "description", "password", "totp", "type", "value"]









    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AccessTfaAddTfaEntryRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AccessTfaAddTfaEntryRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "challenge": obj.get("challenge"),
            "description": obj.get("description"),
            "password": obj.get("password"),
            "totp": obj.get("totp"),
            "type": obj.get("type"),
            "value": obj.get("value")
        })
        return _obj


