# coding: utf-8

"""
    Proxmox Virtual Environment API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 9.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from pve_client.models.pve_boolean import PveBoolean
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AccessRolesReadRoleResponseData(BaseModel):
    """
    AccessRolesReadRoleResponseData
    """ # noqa: E501

    datastore_allocate: Optional[PveBoolean] = Field(default=None, alias="Datastore.Allocate")

    datastore_allocate_space: Optional[PveBoolean] = Field(default=None, alias="Datastore.AllocateSpace")

    datastore_allocate_template: Optional[PveBoolean] = Field(default=None, alias="Datastore.AllocateTemplate")

    datastore_audit: Optional[PveBoolean] = Field(default=None, alias="Datastore.Audit")

    group_allocate: Optional[PveBoolean] = Field(default=None, alias="Group.Allocate")

    mapping_audit: Optional[PveBoolean] = Field(default=None, alias="Mapping.Audit")

    mapping_modify: Optional[PveBoolean] = Field(default=None, alias="Mapping.Modify")

    mapping_use: Optional[PveBoolean] = Field(default=None, alias="Mapping.Use")

    permissions_modify: Optional[PveBoolean] = Field(default=None, alias="Permissions.Modify")

    pool_allocate: Optional[PveBoolean] = Field(default=None, alias="Pool.Allocate")

    pool_audit: Optional[PveBoolean] = Field(default=None, alias="Pool.Audit")

    realm_allocate: Optional[PveBoolean] = Field(default=None, alias="Realm.Allocate")

    realm_allocate_user: Optional[PveBoolean] = Field(default=None, alias="Realm.AllocateUser")

    sdn_allocate: Optional[PveBoolean] = Field(default=None, alias="SDN.Allocate")

    sdn_audit: Optional[PveBoolean] = Field(default=None, alias="SDN.Audit")

    sdn_use: Optional[PveBoolean] = Field(default=None, alias="SDN.Use")

    sys_access_network: Optional[PveBoolean] = Field(default=None, alias="Sys.AccessNetwork")

    sys_audit: Optional[PveBoolean] = Field(default=None, alias="Sys.Audit")

    sys_console: Optional[PveBoolean] = Field(default=None, alias="Sys.Console")

    sys_incoming: Optional[PveBoolean] = Field(default=None, alias="Sys.Incoming")

    sys_modify: Optional[PveBoolean] = Field(default=None, alias="Sys.Modify")

    sys_power_mgmt: Optional[PveBoolean] = Field(default=None, alias="Sys.PowerMgmt")

    sys_syslog: Optional[PveBoolean] = Field(default=None, alias="Sys.Syslog")

    user_modify: Optional[PveBoolean] = Field(default=None, alias="User.Modify")

    vm_allocate: Optional[PveBoolean] = Field(default=None, alias="VM.Allocate")

    vm_audit: Optional[PveBoolean] = Field(default=None, alias="VM.Audit")

    vm_backup: Optional[PveBoolean] = Field(default=None, alias="VM.Backup")

    vm_clone: Optional[PveBoolean] = Field(default=None, alias="VM.Clone")

    vm_config_cdrom: Optional[PveBoolean] = Field(default=None, alias="VM.Config.CDROM")

    vm_config_cpu: Optional[PveBoolean] = Field(default=None, alias="VM.Config.CPU")

    vm_config_cloudinit: Optional[PveBoolean] = Field(default=None, alias="VM.Config.Cloudinit")

    vm_config_disk: Optional[PveBoolean] = Field(default=None, alias="VM.Config.Disk")

    vm_config_hw_type: Optional[PveBoolean] = Field(default=None, alias="VM.Config.HWType")

    vm_config_memory: Optional[PveBoolean] = Field(default=None, alias="VM.Config.Memory")

    vm_config_network: Optional[PveBoolean] = Field(default=None, alias="VM.Config.Network")

    vm_config_options: Optional[PveBoolean] = Field(default=None, alias="VM.Config.Options")

    vm_console: Optional[PveBoolean] = Field(default=None, alias="VM.Console")

    vm_guest_agent_audit: Optional[PveBoolean] = Field(default=None, alias="VM.GuestAgent.Audit")

    vm_guest_agent_file_read: Optional[PveBoolean] = Field(default=None, alias="VM.GuestAgent.FileRead")

    vm_guest_agent_file_system_mgmt: Optional[PveBoolean] = Field(default=None, alias="VM.GuestAgent.FileSystemMgmt")

    vm_guest_agent_file_write: Optional[PveBoolean] = Field(default=None, alias="VM.GuestAgent.FileWrite")

    vm_guest_agent_unrestricted: Optional[PveBoolean] = Field(default=None, alias="VM.GuestAgent.Unrestricted")

    vm_migrate: Optional[PveBoolean] = Field(default=None, alias="VM.Migrate")

    vm_power_mgmt: Optional[PveBoolean] = Field(default=None, alias="VM.PowerMgmt")

    vm_replicate: Optional[PveBoolean] = Field(default=None, alias="VM.Replicate")

    vm_snapshot: Optional[PveBoolean] = Field(default=None, alias="VM.Snapshot")

    vm_snapshot_rollback: Optional[PveBoolean] = Field(default=None, alias="VM.Snapshot.Rollback")

    __properties: ClassVar[List[str]] = ["Datastore.Allocate", "Datastore.AllocateSpace", "Datastore.AllocateTemplate", "Datastore.Audit", "Group.Allocate", "Mapping.Audit", "Mapping.Modify", "Mapping.Use", "Permissions.Modify", "Pool.Allocate", "Pool.Audit", "Realm.Allocate", "Realm.AllocateUser", "SDN.Allocate", "SDN.Audit", "SDN.Use", "Sys.AccessNetwork", "Sys.Audit", "Sys.Console", "Sys.Incoming", "Sys.Modify", "Sys.PowerMgmt", "Sys.Syslog", "User.Modify", "VM.Allocate", "VM.Audit", "VM.Backup", "VM.Clone", "VM.Config.CDROM", "VM.Config.CPU", "VM.Config.Cloudinit", "VM.Config.Disk", "VM.Config.HWType", "VM.Config.Memory", "VM.Config.Network", "VM.Config.Options", "VM.Console", "VM.GuestAgent.Audit", "VM.GuestAgent.FileRead", "VM.GuestAgent.FileSystemMgmt", "VM.GuestAgent.FileWrite", "VM.GuestAgent.Unrestricted", "VM.Migrate", "VM.PowerMgmt", "VM.Replicate", "VM.Snapshot", "VM.Snapshot.Rollback"]


















































    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AccessRolesReadRoleResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AccessRolesReadRoleResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Datastore.Allocate": obj.get("Datastore.Allocate"),
            "Datastore.AllocateSpace": obj.get("Datastore.AllocateSpace"),
            "Datastore.AllocateTemplate": obj.get("Datastore.AllocateTemplate"),
            "Datastore.Audit": obj.get("Datastore.Audit"),
            "Group.Allocate": obj.get("Group.Allocate"),
            "Mapping.Audit": obj.get("Mapping.Audit"),
            "Mapping.Modify": obj.get("Mapping.Modify"),
            "Mapping.Use": obj.get("Mapping.Use"),
            "Permissions.Modify": obj.get("Permissions.Modify"),
            "Pool.Allocate": obj.get("Pool.Allocate"),
            "Pool.Audit": obj.get("Pool.Audit"),
            "Realm.Allocate": obj.get("Realm.Allocate"),
            "Realm.AllocateUser": obj.get("Realm.AllocateUser"),
            "SDN.Allocate": obj.get("SDN.Allocate"),
            "SDN.Audit": obj.get("SDN.Audit"),
            "SDN.Use": obj.get("SDN.Use"),
            "Sys.AccessNetwork": obj.get("Sys.AccessNetwork"),
            "Sys.Audit": obj.get("Sys.Audit"),
            "Sys.Console": obj.get("Sys.Console"),
            "Sys.Incoming": obj.get("Sys.Incoming"),
            "Sys.Modify": obj.get("Sys.Modify"),
            "Sys.PowerMgmt": obj.get("Sys.PowerMgmt"),
            "Sys.Syslog": obj.get("Sys.Syslog"),
            "User.Modify": obj.get("User.Modify"),
            "VM.Allocate": obj.get("VM.Allocate"),
            "VM.Audit": obj.get("VM.Audit"),
            "VM.Backup": obj.get("VM.Backup"),
            "VM.Clone": obj.get("VM.Clone"),
            "VM.Config.CDROM": obj.get("VM.Config.CDROM"),
            "VM.Config.CPU": obj.get("VM.Config.CPU"),
            "VM.Config.Cloudinit": obj.get("VM.Config.Cloudinit"),
            "VM.Config.Disk": obj.get("VM.Config.Disk"),
            "VM.Config.HWType": obj.get("VM.Config.HWType"),
            "VM.Config.Memory": obj.get("VM.Config.Memory"),
            "VM.Config.Network": obj.get("VM.Config.Network"),
            "VM.Config.Options": obj.get("VM.Config.Options"),
            "VM.Console": obj.get("VM.Console"),
            "VM.GuestAgent.Audit": obj.get("VM.GuestAgent.Audit"),
            "VM.GuestAgent.FileRead": obj.get("VM.GuestAgent.FileRead"),
            "VM.GuestAgent.FileSystemMgmt": obj.get("VM.GuestAgent.FileSystemMgmt"),
            "VM.GuestAgent.FileWrite": obj.get("VM.GuestAgent.FileWrite"),
            "VM.GuestAgent.Unrestricted": obj.get("VM.GuestAgent.Unrestricted"),
            "VM.Migrate": obj.get("VM.Migrate"),
            "VM.PowerMgmt": obj.get("VM.PowerMgmt"),
            "VM.Replicate": obj.get("VM.Replicate"),
            "VM.Snapshot": obj.get("VM.Snapshot"),
            "VM.Snapshot.Rollback": obj.get("VM.Snapshot.Rollback")
        })
        return _obj


