# coding: utf-8

"""
    Proxmox Virtual Environment API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 8.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from pve_client.models.pve_boolean import PveBoolean
from pve_client.models.pve_scope_enum import PveScopeEnum
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ClusterJobsCreateJobRequest(BaseModel):
    """
    ClusterJobsCreateJobRequest
    """ # noqa: E501

    comment: Optional[Annotated[str, Field(strict=True, max_length=512)]] = Field(default=None, description="Description for the Job.")

    enable_new: Optional[PveBoolean] = Field(default=None, description="Enable newly synced users immediately.", alias="enable-new")

    enabled: Optional[PveBoolean] = Field(default=None, description="Determines if the job is enabled.")

    realm: Optional[Annotated[str, Field(strict=True, max_length=32)]] = Field(default=None, description="Authentication domain ID")

    remove_vanished: Optional[Annotated[str, Field(strict=True)]] = Field(default='none', description="A semicolon-separated list of things to remove when they or the user vanishes during a sync. The following values are possible: 'entry' removes the user/group when not returned from the sync. 'properties' removes the set properties on existing user/group that do not appear in the source (even custom ones). 'acl' removes acls when the user/group is not returned from the sync. Instead of a list it also can be 'none' (the default).", alias="remove-vanished")

    schedule: Annotated[str, Field(strict=True, max_length=128)] = Field(description="Backup schedule. The format is a subset of `systemd` calendar events.")

    scope: Optional[PveScopeEnum] = Field(default=None, description="Select what to sync.")

    __properties: ClassVar[List[str]] = ["comment", "enable-new", "enabled", "realm", "remove-vanished", "schedule", "scope"]





    @field_validator('realm')
    def realm_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z][A-Za-z0-9.\-_]+$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z][A-Za-z0-9.\-_]+$/")
        return value


    @field_validator('remove_vanished')
    def remove_vanished_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"(?:(?:(?:acl|properties|entry);)*(?:acl|properties|entry))|none", value):
            raise ValueError(r"must validate the regular expression /(?:(?:(?:acl|properties|entry);)*(?:acl|properties|entry))|none/")
        return value


    @field_validator('schedule')
    def schedule_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r".+", value):
            raise ValueError(r"must validate the regular expression /.+/")
        return value




    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ClusterJobsCreateJobRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ClusterJobsCreateJobRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "comment": obj.get("comment"),
            "enable-new": obj.get("enable-new"),
            "enabled": obj.get("enabled"),
            "realm": obj.get("realm"),
            "remove-vanished": obj.get("remove-vanished") if obj.get("remove-vanished") is not None else 'none',
            "schedule": obj.get("schedule"),
            "scope": obj.get("scope")
        })
        return _obj


