# coding: utf-8

"""
    Proxmox Virtual Environment API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 9.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from pve_client.models.pve_boolean import PveBoolean
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ClusterSdnGetVnetsResponseDataInnerPending(BaseModel):
    """
    Changes that have not yet been applied to the running configuration.
    """ # noqa: E501

    alias: Optional[Annotated[str, Field(strict=True, max_length=256)]] = Field(default=None, description="Alias name of the VNet.")

    isolate_ports: Optional[PveBoolean] = Field(default=None, description="If true, sets the isolated property for all interfaces on the bridge of this VNet.", alias="isolate-ports")

    tag: Optional[Annotated[int, Field(le=16777215, strict=True, ge=1)]] = Field(default=None, description="VLAN Tag (for VLAN or QinQ zones) or VXLAN VNI (for VXLAN or EVPN zones).")

    vlanaware: Optional[PveBoolean] = Field(default=None, description="Allow VLANs to pass through this VNet.")

    zone: Optional[StrictStr] = Field(default=None, description="Name of the zone this VNet belongs to.")

    __properties: ClassVar[List[str]] = ["alias", "isolate-ports", "tag", "vlanaware", "zone"]


    @field_validator('alias')
    def alias_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"(?:[\(\)-_.\w\d\s]{0,256})", value):
            raise ValueError(r"must validate the regular expression /(?:[\(\)-_.\w\d\s]{0,256})/")
        return value







    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ClusterSdnGetVnetsResponseDataInnerPending from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ClusterSdnGetVnetsResponseDataInnerPending from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "alias": obj.get("alias"),
            "isolate-ports": obj.get("isolate-ports"),
            "tag": obj.get("tag"),
            "vlanaware": obj.get("vlanaware"),
            "zone": obj.get("zone")
        })
        return _obj


