# coding: utf-8

"""
    Proxmox Virtual Environment API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 8.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from pve_client.models.pve_ring0_addr_field import PveRing0AddrField
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ClusterConfigJoinInfoResponseDataNodelistInner(BaseModel):
    """
    ClusterConfigJoinInfoResponseDataNodelistInner
    """ # noqa: E501

    name: Annotated[str, Field(strict=True)] = Field(description="The cluster node name.")

    nodeid: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Node id for this node.")

    pve_addr: Annotated[str, Field(strict=True)]

    pve_fp: Annotated[str, Field(strict=True)] = Field(description="Certificate SHA 256 fingerprint.")

    quorum_votes: Annotated[int, Field(strict=True, ge=0)]

    ring0_addr: Optional[PveRing0AddrField] = Field(default=None, description="Address and priority information of a single corosync link. (up to 8 links supported; link0..link7)")

    __properties: ClassVar[List[str]] = ["name", "nodeid", "pve_addr", "pve_fp", "quorum_votes", "ring0_addr"]


    @field_validator('name')
    def name_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^(?:[a-zA-Z0-9](?:[a-zA-Z0-9\-]*[a-zA-Z0-9])?)$", value):
            raise ValueError(r"must validate the regular expression /^(?:[a-zA-Z0-9](?:[a-zA-Z0-9\-]*[a-zA-Z0-9])?)$/")
        return value



    @field_validator('pve_addr')
    def pve_addr_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^(?:(?:[0-9a-fA-F]{0,4}:){2,7}[0-9a-fA-F]{0,4}|(?:[0-9]{1,3}\.){3}[0-9]{1,3})$", value):
            raise ValueError(r"must validate the regular expression /^(?:(?:[0-9a-fA-F]{0,4}:){2,7}[0-9a-fA-F]{0,4}|(?:[0-9]{1,3}\.){3}[0-9]{1,3})$/")
        return value


    @field_validator('pve_fp')
    def pve_fp_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"([A-Fa-f0-9]{2}:){31}[A-Fa-f0-9]{2}", value):
            raise ValueError(r"must validate the regular expression /([A-Fa-f0-9]{2}:){31}[A-Fa-f0-9]{2}/")
        return value





    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ClusterConfigJoinInfoResponseDataNodelistInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of ring0_addr
        if self.ring0_addr:
            _dict['ring0_addr'] = self.ring0_addr.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ClusterConfigJoinInfoResponseDataNodelistInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "nodeid": obj.get("nodeid"),
            "pve_addr": obj.get("pve_addr"),
            "pve_fp": obj.get("pve_fp"),
            "quorum_votes": obj.get("quorum_votes"),
            "ring0_addr": PveRing0AddrField.from_dict(obj["ring0_addr"]) if obj.get("ring0_addr") is not None else None
        })
        return _obj


