# coding: utf-8

"""
    Proxmox Virtual Environment API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 8.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from pve_client.models.pve_boolean import PveBoolean
from pve_client.models.pve_mode_mode_enum import PveModeModeEnum
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ClusterNotificationsGetMatcherResponseData(BaseModel):
    """
    ClusterNotificationsGetMatcherResponseData
    """ # noqa: E501

    comment: Optional[StrictStr] = Field(default=None, description="Comment")

    digest: Optional[Annotated[str, Field(strict=True, max_length=64)]] = Field(default=None, description="Prevent changes if current configuration file has a different digest. This can be used to prevent concurrent modifications.")

    disable: Optional[PveBoolean] = Field(default=None, description="Disable this matcher")

    invert_match: Optional[PveBoolean] = Field(default=None, description="Invert match of the whole matcher", alias="invert-match")

    match_calendar: Optional[List[StrictStr]] = Field(default=None, description="Match notification timestamp", alias="match-calendar")

    match_field: Optional[List[StrictStr]] = Field(default=None, description="Metadata fields to match (regex or exact match). Must be in the form (regex|exact):<field>=<value>", alias="match-field")

    match_severity: Optional[List[StrictStr]] = Field(default=None, description="Notification severities to match", alias="match-severity")

    mode: Optional[PveModeModeEnum] = Field(default=None, description="Choose between 'all' and 'any' for when multiple properties are specified")

    name: Annotated[str, Field(strict=True)] = Field(description="Name of the matcher.")

    target: Optional[List[Annotated[str, Field(strict=True)]]] = Field(default=None, description="Targets to notify on match")

    __properties: ClassVar[List[str]] = ["comment", "digest", "disable", "invert-match", "match-calendar", "match-field", "match-severity", "mode", "name", "target"]










    @field_validator('name')
    def name_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z][A-Za-z0-9_]*$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z][A-Za-z0-9_]*$/")
        return value




    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ClusterNotificationsGetMatcherResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ClusterNotificationsGetMatcherResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "comment": obj.get("comment"),
            "digest": obj.get("digest"),
            "disable": obj.get("disable"),
            "invert-match": obj.get("invert-match"),
            "match-calendar": obj.get("match-calendar"),
            "match-field": obj.get("match-field"),
            "match-severity": obj.get("match-severity"),
            "mode": obj.get("mode"),
            "name": obj.get("name"),
            "target": obj.get("target")
        })
        return _obj


