# coding: utf-8

"""
    Proxmox Virtual Environment API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 8.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from pve_client.models.pve_nodes_status_enum import PveNodesStatusEnum
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class NodesGetNodesResponseDataInner(BaseModel):
    """
    NodesGetNodesResponseDataInner
    """ # noqa: E501

    cpu: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="CPU utilization.")

    level: Optional[StrictStr] = Field(default=None, description="Support level.")

    maxcpu: Optional[StrictInt] = Field(default=None, description="Number of available CPUs.")

    maxmem: Optional[StrictInt] = Field(default=None, description="Number of available memory in bytes.")

    mem: Optional[StrictInt] = Field(default=None, description="Used memory in bytes.")

    node: Annotated[str, Field(strict=True)] = Field(description="The cluster node name.")

    ssl_fingerprint: Optional[StrictStr] = Field(default=None, description="The SSL fingerprint for the node certificate.")

    status: PveNodesStatusEnum = Field(description="Node status.")

    uptime: Optional[StrictInt] = Field(default=None, description="Node uptime in seconds.")

    id: Optional[StrictStr] = Field(default=None, description="Resource id of the form \"node/<name>\".")

    type: Optional[StrictStr] = Field(default=None, description="Resource type discriminator.")

    disk: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Used disk space in bytes.")

    maxdisk: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Total disk space in bytes.")

    __properties: ClassVar[List[str]] = ["cpu", "level", "maxcpu", "maxmem", "mem", "node", "ssl_fingerprint", "status", "uptime", "id", "type", "disk", "maxdisk"]







    @field_validator('node')
    def node_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^(?:[a-zA-Z0-9](?:[a-zA-Z0-9\-]*[a-zA-Z0-9])?)$", value):
            raise ValueError(r"must validate the regular expression /^(?:[a-zA-Z0-9](?:[a-zA-Z0-9\-]*[a-zA-Z0-9])?)$/")
        return value






    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['node']):
            raise ValueError("must be one of enum values ('node')")
        return value





    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NodesGetNodesResponseDataInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NodesGetNodesResponseDataInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "cpu": obj.get("cpu"),
            "level": obj.get("level"),
            "maxcpu": obj.get("maxcpu"),
            "maxmem": obj.get("maxmem"),
            "mem": obj.get("mem"),
            "node": obj.get("node"),
            "ssl_fingerprint": obj.get("ssl_fingerprint"),
            "status": obj.get("status"),
            "uptime": obj.get("uptime"),
            "id": obj.get("id"),
            "type": obj.get("type"),
            "disk": obj.get("disk"),
            "maxdisk": obj.get("maxdisk")
        })
        return _obj


