# coding: utf-8

"""
    Proxmox Virtual Environment API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 8.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class NodesDisksGetLvmthinResponseDataInner(BaseModel):
    """
    NodesDisksGetLvmthinResponseDataInner
    """ # noqa: E501

    lv: StrictStr = Field(description="The name of the thinpool.")

    lv_size: StrictInt = Field(description="The size of the thinpool in bytes.")

    metadata_size: StrictInt = Field(description="The size of the metadata lv in bytes.")

    metadata_used: StrictInt = Field(description="The used bytes of the metadata lv.")

    used: StrictInt = Field(description="The used bytes of the thinpool.")

    vg: StrictStr = Field(description="The associated volume group.")

    __properties: ClassVar[List[str]] = ["lv", "lv_size", "metadata_size", "metadata_used", "used", "vg"]









    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NodesDisksGetLvmthinResponseDataInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NodesDisksGetLvmthinResponseDataInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "lv": obj.get("lv"),
            "lv_size": obj.get("lv_size"),
            "metadata_size": obj.get("metadata_size"),
            "metadata_used": obj.get("metadata_used"),
            "used": obj.get("used"),
            "vg": obj.get("vg")
        })
        return _obj


