# flake8: noqa

# import apis into api package
from pve_client.api.access_api import AccessApi
from pve_client.api.access_acl_api import AccessAclApi
from pve_client.api.access_domains_api import AccessDomainsApi
from pve_client.api.access_groups_api import AccessGroupsApi
from pve_client.api.access_openid_api import AccessOpenidApi
from pve_client.api.access_roles_api import AccessRolesApi
from pve_client.api.access_tfa_api import AccessTfaApi
from pve_client.api.access_ticket_api import AccessTicketApi
from pve_client.api.access_users_api import AccessUsersApi
from pve_client.api.cluster_api import ClusterApi
from pve_client.api.cluster_acme_api import ClusterAcmeApi
from pve_client.api.cluster_backup_api import ClusterBackupApi
from pve_client.api.cluster_backup_info_api import ClusterBackupInfoApi
from pve_client.api.cluster_bulk_action_api import ClusterBulkActionApi
from pve_client.api.cluster_ceph_api import ClusterCephApi
from pve_client.api.cluster_config_api import ClusterConfigApi
from pve_client.api.cluster_firewall_api import ClusterFirewallApi
from pve_client.api.cluster_ha_api import ClusterHaApi
from pve_client.api.cluster_jobs_api import ClusterJobsApi
from pve_client.api.cluster_mapping_api import ClusterMappingApi
from pve_client.api.cluster_metrics_api import ClusterMetricsApi
from pve_client.api.cluster_notifications_api import ClusterNotificationsApi
from pve_client.api.cluster_options_api import ClusterOptionsApi
from pve_client.api.cluster_replication_api import ClusterReplicationApi
from pve_client.api.cluster_sdn_api import ClusterSdnApi
from pve_client.api.lxc_api import LxcApi
from pve_client.api.nodes_api import NodesApi
from pve_client.api.nodes_aplinfo_api import NodesAplinfoApi
from pve_client.api.nodes_apt_api import NodesAptApi
from pve_client.api.nodes_capabilities_api import NodesCapabilitiesApi
from pve_client.api.nodes_ceph_api import NodesCephApi
from pve_client.api.nodes_certificates_api import NodesCertificatesApi
from pve_client.api.nodes_config_api import NodesConfigApi
from pve_client.api.nodes_disks_api import NodesDisksApi
from pve_client.api.nodes_dns_api import NodesDnsApi
from pve_client.api.nodes_firewall_api import NodesFirewallApi
from pve_client.api.nodes_hardware_api import NodesHardwareApi
from pve_client.api.nodes_hosts_api import NodesHostsApi
from pve_client.api.nodes_network_api import NodesNetworkApi
from pve_client.api.nodes_replication_api import NodesReplicationApi
from pve_client.api.nodes_scan_api import NodesScanApi
from pve_client.api.nodes_sdn_api import NodesSdnApi
from pve_client.api.nodes_services_api import NodesServicesApi
from pve_client.api.nodes_status_api import NodesStatusApi
from pve_client.api.nodes_storage_api import NodesStorageApi
from pve_client.api.nodes_subscription_api import NodesSubscriptionApi
from pve_client.api.nodes_tasks_api import NodesTasksApi
from pve_client.api.nodes_time_api import NodesTimeApi
from pve_client.api.nodes_vzdump_api import NodesVzdumpApi
from pve_client.api.pools_api import PoolsApi
from pve_client.api.qemu_api import QemuApi
from pve_client.api.storage_api import StorageApi
from pve_client.api.version_api import VersionApi

